### ISSUE TITLE
Can MERCI be used to evaluate MT transfer between any two types of cells?

### ISSUE THREAD

**Issue by Yujj1123** [shyhihihi/MERCI#2]
Thanks for developing such a powerful tool for the evaluation of MT transfer!Should MERCI be used only to evaluate MT transfer between tumor cells and T cells?Or can it be used for any two types of cells?

**Comment by shyhihihi** [comment]
Thanks for your interests.
Currently, we have not tested other cell types (ongoing).
Theoretically, MERCI is able to evaluate MT transfer signal and predict mitochondrial receivers for any two cell types derived from a same sample. Please make sure the read coverage of mitochondrial genome for each input cell is sufficient. We recommend > 1,000 reads uniquely mapping to MT genome (this information could be obtained from output of MERCI-mtSNP).

**Comment by Yujj1123** [comment]
Thank you for your prompt and detailed response. 
It's exciting to hear about the potential of MERCI in evaluating MT transfer signals and predicting mitochondrial receivers for any two cell types. This holds significant importance for our research project.
If there are any further developments or updates, we would be eager to stay informed and maintain close attention to your work. Once again, we appreciate your insightful response.
